### ISSUE TITLE
default behaviour for exceptions raised when running tests?

### ISSUE THREAD

**Issue by ebo** [TestAnything/test-anything-protocol#2]
Last summer my intern and I developed a TAP producer/consumer/dashboard which conforms to NASA agency guidelines (many CI/CD tools break a number of restrictions and VKDash was developed to work within those constraints).  

While working on one of our projects the unit tests themselves triggered an internal exception, and the TAP messages were never generated.  I added an atexit handler specifically to handle dumping the messages, and I also wrote in a bail_out with the last error message.  Should this be turned on by default?  Or should I have it off by default and have the user specifically turn it on?

BTW, VKDash is in the process of being open-sourced,so I will email you about it when we publically release it.

**Comment by kinow** [comment]
Not sure. It's normal to have flags like `verbose` in test harness tools that enable more information. And there are other tools like JUnit that by default emit the errors in XML (we can assume it would be doing the same should it had been using TAP instead).

I think it's better for the specification to stay more neutral, focusing on what can be emitted by producers, but leave up to the implementations to decide whether to include error messages.

Just my 0.02 cents.

Bruno

ps: looking forward to the release of VKDash!!

**Comment by ebo** [comment]
8-)  Thanks.

I understand the stance, and agree with it.  I'm just not sure which 
way to ump on this one.  I guess given my 'druthers I would make the 
atexit default True or always on -- that way the processed tests will 
provide output.  As for (P)FUnit, those were developed by other 
organizations for for their own needs.  I have convinced them to develop 
a TAP compliant result formatter (so that test results can be compared 
across multiple languages -- (P)FUnit is a Fortran testing tool).  I'll 
await other opinions and move forward.

BTW, I got one of the remaining two signoffs today, so just one more + 
processing 8-)

   Cheers!

   EBo --

**Comment by ap** [comment]
The atexit should maybe be enabled by default, but bail_out should be disabled by default (though in that case you should still spit out the error, maybe as a diag):

1. TAP’s design presumes tests *not* exiting early, even on error – getting the opposite behaviour is somewhat unnatural. The tests aren’t necessarily being run by the process that’s parsing the TAP stream – they may have been run by some entirely separate process in a completely different environment… like on a microcontroller connected over a serial line.

2. TAP’s notion of the plan exists so a parser can know whether a TAP stream is complete or not, *even if* the test somehow managed to silently/successfully exit early, and even in cases where no out-of-band information (like the exit status of the test program) exists.

The idea is for TAP to be stupidly simple to emit, and to put all the smarts in the parser, primarily so that the tests run in an execution environment as similar to the normal one for the code under test as possible. (No big testing library/framework with maybe lots of extra classes/namespaces, maybe complex init at process start, maybe needing per-thread setup, maybe etc etc…) Secondarily as a side effect, this also makes TAP really easy to generate from just about any execution environment that has any notion of “output” at all, even before you have bootstrapped any complex development tooling (as in the above microcontroller scenario; you barely need more than machine code, in a pinch).

In those terms, the atexit handler is somewhat in conflict between principles. Not touching the execution environment argues against it, but making sure that all generated TAP gets out argues in favour. I think overall it makes more sense to make it an option that is enabled by default.

**Comment by ebo** [comment]
Thank you Ap for your principled response.  I full agree and will modify as my understanding of your suggestions:  atexit optional but enabled by default, and emit a diagnostic message notifying user of unexpected termination and include the last error message.

As a note, the reason that I added this in the first place is that a code modification killed the tests, and the results were not being written.
